name: Test Build, Lint and Setup

on:
  push:
  pull_request:

jobs:
  build-lint-setup:
    runs-on: ubuntu-latest
    # Node.js version is defined as 18.x as a matrix strategy
    strategy:
      matrix:
        node-version: [18.x]

    # Steps to run the job
    steps:
      # Clones the repository
      - uses: actions/checkout@v3

      # Sets up pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: '8.6.0'

      # Sets up Node.js and caches with pnpm
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: 'pnpm'

      # Installs dependencies using pnpm
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # Builds the project using pnpm
      - name: Build
        run: pnpm build

      # Runs lint using pnpm
      - name: Lint
        run: pnpm lint
